### ISSUE TITLE
Poor results with coap/block_optimization branch

### ISSUE THREAD

**Issue by kb2ma** [kb2ma/RIOT#29]
Message from Ashim Asharaph [1]:

So I decided to use the gcoap blockwise transfer from PR #11057 with a GET request. On native it works fine. When testing on real hardware using two samr21-xpro boards with one running the gnrc _border_router example, the block transfer only completes successfully about 50% of the time with a 50kB file and 128 byte packets. The application says "gcoap: timeout for msg ID xxxxx". The time at which the timeout occurs seems random at any point during the blockwise transfer.

The final plan is to integrate the gcoap with wakaama and use both together for an OTA firmware update. When the integrated version is used, the success rate is about 5%. Are there any parameters or code that could be tweaked on either the RIOT application or on the Californium file server to improve the success rate? What could be causing the issue or how can I try to determine the problem?

[1] https://lists.riot-os.org/pipermail/devel/2019-May/006185.html

**Comment by kb2ma** [comment]
Sorry to hear you're having issues. Let me make sure I understand. Let's say node A is the border router, and node B is the leaf node. Is node B making a GET request to node A, and is node A returning the block in the response? Are you using confirmable messages or non-confirmable? If you could post your application code somewhere, I can review it.

I also will try to recreate this scenario and let you know my results.

**Comment by kb2ma** [comment]
I was able to successfully send a large payload blockwise on samr21-xpro boards. The scenario below uses a block1 POST. I was able to send 3 60 kB payloads for each of 32-byte and 64-byte blocks. There were from 0 to 2 retransmissions in each trial.

See the description below, and please give it a try.

## Setup
### Linux host
[Block1 client](https://github.com/kb2ma/riot-coap-pytest/blob/master/block1_client.py) based on aiocoap

### RIOT Border router
gnrc_border_router on samr21-xpro

### RIOT Leaf node
gcoap-block-server on samr21-xpro

## Procedure
To set up the border router and leaf node, follow the instructions from my test suite, [riot-coap-pytest](https://github.com/kb2ma/riot-coap-pytest/blob/master/README.md). See the section labeled _rpl2os_. Also, if you're not familiar with aiocoap, see the installation instructions in the _Materials_ section.

To set up block1_client, see the usage instructions at the top of the file. To create a large payload, simply multiply the payload in the main function. For example, for a 60 kB payload:

    payload *= 1000

**Comment by brent7984** [comment]
Hi there, my name is Brenton, I'm working with Ashim on this project. Thank you for the advise, its sending files correctly now using libcoap's POST. We were using Californiums file server before, which was the issue. We are now trying to use riotboot to update our firmware OTA. I initially flashed a board with the "riotboot_flashwrite" example using the "riotboot/flash" command. I then managed to update the board with a wakaama example. That worked fine, but when i try to re update the board with another image i received a COAP 4.04 error. 
Note, the libcoap command used was "./coap-client -m post coap://[2001:db8::7b65:758:bdfc:55d6]/flashwrite \       -f wakaama-slot1.riot.bin -b 64".
Do you have any ideas on what could be wrong.

Kind regards
Brenton

**Comment by kb2ma** [comment]
Glad to head you made it past the block issue. I also plan to set up another example where the leaf node requests the large payload with a GET, as you were doing originally. There may be an issue with gcoap's request handling.

I have not used riotboot_flashwrite. I see that the app includes the /flashwrite resource. However, you also say that you added a wakaama example. Are you sure the riotboot_flashwrite handler still is available? In addition, wakaama uses its own CoAP implementation. Is wakaama's CoAP listening on port 5683? In that case, it would not know about /flashwrite.

**Comment by brent7984** [comment]
Hi, it works. You were right about the COAP listening port. We now have a fully functional LWM2M Firmware OTA mechanism. Thank you for all of your help.

With regards
Brenton

**Comment by kb2ma** [comment]
I was able to successfully retrieve a large payload blockwise on samr21-xpro boards. The scenario below uses a block2 GET. I was able to receive 3 50 kB payloads for 32-byte blocks. There were 1 or 2 retransmissions in each trial. See the description below.

## Setup
### Linux host
[server.py](https://github.com/chrysn/aiocoap/blob/master/server.py) example from aiocoap. Must incorporate fix in [#158](https://github.com/chrysn/aiocoap/pull/158) to accept block size in request.

### RIOT Border router
gnrc_border_router on samr21-xpro

### RIOT Leaf node
[gcoap-cli-plus](https://github.com/kb2ma/riot-apps/tree/kb2ma-master/gcoap-cli-plus) on samr21-xpro. 

## Procedure
To set up the border router and leaf node, follow the instructions from my test suite, [riot-coap-pytest](https://github.com/kb2ma/riot-coap-pytest/blob/master/README.md). See the section labeled _rpl2os_. Also, if you're not familiar with aiocoap, see the installation instructions in the _Materials_ section.

To specify a 32-byte payload in gcoap-cli-plus, include the `-b 32` option in the request.

To create a large payload in the aiocoap server, increase the size of the content in BlockResource.set_content() in server.py.
